#!/bin/bash

if [ "$#" -ne 5 ]
then
  echo "
        Error: Incorrect number of arguments supplied.
        Usage: ./run_ec2_exp_runner.sh ProcessorType(intel/amd) InstanceType(e.g. c5.12xlarge, c5.4xlarge) NoOfCPUs(e.g. 8,12,24) ExpType(redis/memcached).
        "
  exit
fi

processor_type=$1
instance_type=$2
no_of_cores=$3
exp_type=$4
instance_no=$5

for i in {1..1};
do
  if [[ $exp_type == "nginx" ]]
  then
    echo "*** Running nginx exp: ./run_ec2_exp_nginx.sh $processor_type $instance_type $no_of_cores"
    ./run_ec2_exp_nginx.sh $processor_type $instance_type $no_of_cores &
    ./run_ec2_exp_nginx.sh $processor_type $instance_type $no_of_cores &
    #./run_ec2_exp_nginx.sh $processor_type $instance_type $no_of_cores &
    #./run_ec2_exp_nginx.sh $processor_type $instance_type $no_of_cores &
  elif [[ $exp_type == "memcached"  ]]
  then
    echo "*** Running mc or redis: ./run_ec2_exp.sh $processor_type $instance_type $no_of_cores $exp_type $instance_no"
    ./run_ec2_exp.sh $processor_type $instance_type $no_of_cores $exp_type $instance_no &
    ./run_ec2_exp.sh $processor_type $instance_type $no_of_cores $exp_type $instance_no &
    ./run_ec2_exp.sh $processor_type $instance_type $no_of_cores $exp_type $instance_no &
    ./run_ec2_exp.sh $processor_type $instance_type $no_of_cores $exp_type $instance_no &
  else # mlc
    case_no="case_2"
    
    echo "*** Running mlc: ./run_ec2_exp_mlc.sh $processor_type $instance_type $no_of_cores $case_no (primary/secondary)"
    
    #intialize the vms
    for i in {1..2}; do
      ./run_ec2_exp_mlc.sh $processor_type $instance_type $no_of_cores $case_no secondary init instance_$i.txt
    done
    
    echo "Done initializing all the vms. Now running the tests .... "
     
    # run the exp
    ./run_ec2_exp_mlc.sh $processor_type $instance_type $no_of_cores $case_no primary run instance_1.txt &
    #for i in {2..6}; do
    #  ./run_ec2_exp_mlc.sh $processor_type $instance_type $no_of_cores $case_no secondary run instance_$i.txt &
    #done
    
    #./run_ec2_exp_mlc.sh $processor_type $instance_type $no_of_cores $case_no secondary run instance_2.txt
  fi
  #sleep 60m
done
